// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsillgjobfipoftvtnvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzaWxsZ2pvYmZpcG9mdHZ0bnZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTI0NTQsImV4cCI6MjA2NTkyODQ1NH0.C3mqas_Ouke2h4reg_YJDoUO1ioxEk83Z-G33p_GL-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);